import { Injectable, Logger } from '@nestjs/common';
import PDFDocument = require('pdfkit');
import { PrismaService } from '../../prisma/prisma.service';

@Injectable()
export class DocumentGenerationService {
  private readonly logger = new Logger(DocumentGenerationService.name);

  constructor(private readonly prisma: PrismaService) {}

  async generatePurchaseOrderPdf(purchaseOrderId: string): Promise<Buffer> {
    const po = await this.prisma.purchaseOrder.findUnique({
      where: { id: purchaseOrderId },
      include: { supplier: true, items: true }
    });

    if (!po) {
      throw new Error(`PurchaseOrder ${purchaseOrderId} not found.`);
    }

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        // Header
        doc.fontSize(20).text('PURCHASE ORDER', { align: 'center' });
        doc.moveDown();
        
        doc.fontSize(12).text(`Order Number: ${po.orderNumber}`);
        doc.text(`Date: ${po.createdAt.toDateString()}`);
        doc.text(`Status: ${po.status}`);
        
        doc.moveDown();
        doc.text(`Supplier: ${po.supplier?.name || 'Unknown'}`);
        if (po.supplier?.email) doc.text(`Email: ${po.supplier.email}`);
        
        doc.moveDown();
        doc.text('Items:', { underline: true });
        
        let y = doc.y + 10;
        doc.fontSize(10);
        doc.text('SKU', 50, y);
        doc.text('Qty', 200, y);
        doc.text('Price', 300, y);
        doc.text('Total', 400, y);
        
        y += 20;
        
        for (const item of po.items) {
          doc.text(item.productId, 50, y);
          doc.text(item.quantity.toString(), 200, y);
          doc.text(`$${Number(item.unitCost).toFixed(2)}`, 300, y);
          doc.text(`$${Number(item.totalCost).toFixed(2)}`, 400, y);
          y += 20;
        }
        
        doc.moveDown(2);
        doc.fontSize(12).text(`Total Amount: $${Number(po.totalAmount).toFixed(2)}`, { align: 'right' });
        
        // Footer
        doc.fontSize(10).text('Generated by DukanAI Enterprise ERP', 50, 700, { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  async generateGrnPdf(grnId: string): Promise<Buffer> {
    const grn = await this.prisma.goodsReceipt.findUnique({
      where: { id: grnId },
      include: { purchaseOrder: true, lines: true }
    });

    if (!grn) throw new Error(`GRN ${grnId} not found`);

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        doc.fontSize(20).text('GOODS RECEIPT NOTE', { align: 'center' });
        doc.moveDown();
        
        doc.fontSize(12).text(`GRN Number: ${grn.grnNumber}`);
        doc.text(`Date: ${grn.createdAt.toDateString()}`);
        doc.text(`Status: ${grn.status}`);
        if (grn.purchaseOrder) doc.text(`PO Number: ${grn.purchaseOrder.orderNumber}`);
        
        doc.moveDown();
        doc.text('Received Items:', { underline: true });
        
        let y = doc.y + 10;
        doc.fontSize(10);
        doc.text('SKU', 50, y);
        doc.text('Expected', 200, y);
        doc.text('Received', 300, y);
        doc.text('Rejected', 400, y);
        
        y += 20;
        
        for (const item of grn.lines) {
          doc.text(item.productId, 50, y);
          doc.text(item.orderedQuantity.toString(), 200, y);
          doc.text(item.receivedQuantity.toString(), 300, y);
          doc.text(item.rejectedQuantity.toString(), 400, y);
          y += 20;
        }

        doc.fontSize(10).text('Generated by DukanAI Enterprise ERP', 50, 700, { align: 'center' });
        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  async generateVendorBillPdf(billId: string): Promise<Buffer> {
    const bill = await this.prisma.vendorBill.findUnique({
      where: { id: billId },
      include: { supplier: true, purchaseOrder: true }
    });

    if (!bill) throw new Error(`Vendor Bill ${billId} not found`);

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        doc.fontSize(20).text('PAYMENT ADVICE / VENDOR BILL', { align: 'center' });
        doc.moveDown();
        
        doc.fontSize(12).text(`Bill Number: ${bill.billNumber}`);
        doc.text(`Date: ${bill.createdAt.toDateString()}`);
        doc.text(`Status: ${bill.status}`);
        if (bill.purchaseOrder) doc.text(`PO Number: ${bill.purchaseOrder.orderNumber}`);
        if (bill.supplier) doc.text(`Supplier: ${bill.supplier.name}`);
        
        doc.moveDown();
        const subtotal = Number(bill.totalAmount) - Number(bill.taxAmount || 0) + Number(bill.discountAmount || 0);
        doc.fontSize(14).text(`Subtotal: $${subtotal.toFixed(2)}`);
        doc.text(`Tax: $${Number(bill.taxAmount || 0).toFixed(2)}`);
        doc.text(`Discount: $${Number(bill.discountAmount || 0).toFixed(2)}`);
        doc.fontSize(16).text(`Total Amount: $${Number(bill.totalAmount).toFixed(2)}`);
        
        doc.fontSize(10).text('Generated by DukanAI Enterprise ERP', 50, 700, { align: 'center' });
        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  async generatePurchaseReturnPdf(returnId: string): Promise<Buffer> {
    const ret = await this.prisma.purchaseReturn.findUnique({
      where: { id: returnId },
      include: { supplier: true, purchaseOrder: true, lines: true }
    });

    if (!ret) throw new Error(`Purchase Return ${returnId} not found`);

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        doc.fontSize(20).text('PURCHASE RETURN (RMA)', { align: 'center' });
        doc.moveDown();
        
        doc.fontSize(12).text(`Return Number: ${ret.returnNumber}`);
        doc.text(`Date: ${ret.createdAt.toDateString()}`);
        doc.text(`Status: ${ret.status}`);
        if (ret.purchaseOrder) doc.text(`PO Number: ${ret.purchaseOrder.orderNumber}`);
        if (ret.supplier) doc.text(`Supplier: ${ret.supplier.name}`);
        
        doc.moveDown();
        doc.text('Returned Items:', { underline: true });
        
        let y = doc.y + 10;
        doc.fontSize(10);
        doc.text('SKU', 50, y);
        doc.text('Quantity', 200, y);
        doc.text('Reason', 300, y);
        
        y += 20;
        
        for (const item of ret.lines) {
          doc.text(item.productId, 50, y);
          doc.text(item.returnQuantity.toString(), 200, y);
          doc.text(item.reason || 'N/A', 300, y);
          y += 20;
        }

        doc.moveDown(2);
        doc.fontSize(12).text(`Total Refund Amount: $${Number(ret.totalAmount).toFixed(2)}`, { align: 'right' });
        
        doc.fontSize(10).text('Generated by DukanAI Enterprise ERP', 50, 700, { align: 'center' });
        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  async generateSupplierCreditPdf(creditId: string): Promise<Buffer> {
    const credit = await this.prisma.supplierCreditNote.findUnique({
      where: { id: creditId },
      include: { supplier: true, vendorBill: true }
    });

    if (!credit) throw new Error(`Supplier Credit ${creditId} not found`);

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        doc.fontSize(20).text('SUPPLIER CREDIT NOTE', { align: 'center' });
        doc.moveDown();
        
        doc.fontSize(12).text(`Credit Number: ${credit.creditNumber}`);
        doc.text(`Date: ${credit.createdAt.toDateString()}`);
        doc.text(`Status: ${credit.status}`);
        if (credit.vendorBill) doc.text(`Related Bill: ${credit.vendorBill.billNumber}`);
        if (credit.supplier) doc.text(`Supplier: ${credit.supplier.name}`);
        
        doc.moveDown();
        doc.fontSize(16).text(`Credit Amount: $${Number(credit.totalAmount).toFixed(2)}`);
        
        doc.fontSize(10).text('Generated by DukanAI Enterprise ERP', 50, 700, { align: 'center' });
        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}
