export enum ValidationCategory {
  DOMAIN = 'DOMAIN',
  CROSS_DOMAIN = 'CROSS_DOMAIN',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  ENVIRONMENT = 'ENVIRONMENT',
  STARTUP = 'STARTUP',
  RUNTIME = 'RUNTIME',
}
