export enum CustomerType {
  RETAIL = 'RETAIL',
  WHOLESALE = 'WHOLESALE',
  DISTRIBUTOR = 'DISTRIBUTOR',
  CORPORATE = 'CORPORATE',
  DEALER = 'DEALER',
  WALKIN = 'WALKIN',
  VIP = 'VIP',
  GOVERNMENT = 'GOVERNMENT',
  EDUCATIONAL = 'EDUCATIONAL',
  HOSPITAL = 'HOSPITAL',
  FRANCHISE = 'FRANCHISE',
  ONLINE = 'ONLINE'
}

export enum CustomerLifecycleStatus {
  LEAD = 'LEAD',
  PROSPECT = 'PROSPECT',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  ARCHIVED = 'ARCHIVED'
}

export enum ContactRole {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  ACCOUNTS = 'ACCOUNTS',
  PURCHASE = 'PURCHASE',
  SALES = 'SALES',
  SUPPORT = 'SUPPORT'
}

export enum AddressType {
  BILLING = 'BILLING',
  SHIPPING = 'SHIPPING',
  OFFICE = 'OFFICE',
  WAREHOUSE = 'WAREHOUSE'
}

export enum KycStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED'
}
